# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Typing

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ColorTransform(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 7

    # ColorTransform
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColorTransform
    def RMul(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ColorTransform
    def GMul(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # ColorTransform
    def BMul(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # ColorTransform
    def Alpha(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(3))
    # ColorTransform
    def RAdd(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # ColorTransform
    def GAdd(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(5))
    # ColorTransform
    def BAdd(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))

def CreateColorTransform(builder, rMul, gMul, bMul, alpha, rAdd, gAdd, bAdd):
    builder.Prep(1, 7)
    builder.PrependUint8(bAdd)
    builder.PrependUint8(gAdd)
    builder.PrependUint8(rAdd)
    builder.PrependUint8(alpha)
    builder.PrependUint8(bMul)
    builder.PrependUint8(gMul)
    builder.PrependUint8(rMul)
    return builder.Offset()
