# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Typing

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HalfMatrix2x3(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # HalfMatrix2x3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HalfMatrix2x3
    def A(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # HalfMatrix2x3
    def B(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # HalfMatrix2x3
    def C(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # HalfMatrix2x3
    def D(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # HalfMatrix2x3
    def Tx(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # HalfMatrix2x3
    def Ty(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))

def CreateHalfMatrix2x3(builder, a, b, c, d, tx, ty):
    builder.Prep(2, 12)
    builder.PrependInt16(ty)
    builder.PrependInt16(tx)
    builder.PrependInt16(d)
    builder.PrependInt16(c)
    builder.PrependInt16(b)
    builder.PrependInt16(a)
    return builder.Offset()
