# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Typing

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Matrix2x3(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # Matrix2x3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Matrix2x3
    def A(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Matrix2x3
    def B(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Matrix2x3
    def C(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Matrix2x3
    def D(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # Matrix2x3
    def Tx(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # Matrix2x3
    def Ty(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))

def CreateMatrix2x3(builder, a, b, c, d, tx, ty):
    builder.Prep(4, 24)
    builder.PrependFloat32(ty)
    builder.PrependFloat32(tx)
    builder.PrependFloat32(d)
    builder.PrependFloat32(c)
    builder.PrependFloat32(b)
    builder.PrependFloat32(a)
    return builder.Offset()
