# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Typing

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Rect(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Rect
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Rect
    def Left(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Rect
    def Top(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Rect
    def Right(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Rect
    def Bottom(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateRect(builder, left, top, right, bottom):
    builder.Prep(4, 16)
    builder.PrependFloat32(bottom)
    builder.PrependFloat32(right)
    builder.PrependFloat32(top)
    builder.PrependFloat32(left)
    return builder.Offset()
