# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CompressedMovieClip(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CompressedMovieClip()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCompressedMovieClip(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CompressedMovieClip
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CompressedMovieClip
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # CompressedMovieClip
    def ExportNameRefId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return None

    # CompressedMovieClip
    def Framerate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CompressedMovieClip
    def FramesCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # CompressedMovieClip
    def UnknownBool(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CompressedMovieClip
    def ChildrenIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # CompressedMovieClip
    def ChildrenIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # CompressedMovieClip
    def ChildrenIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CompressedMovieClip
    def ChildrenIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # CompressedMovieClip
    def ChildrenNameRefIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CompressedMovieClip
    def ChildrenNameRefIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # CompressedMovieClip
    def ChildrenNameRefIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CompressedMovieClip
    def ChildrenNameRefIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # CompressedMovieClip
    def ChildrenBlending(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CompressedMovieClip
    def ChildrenBlendingAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # CompressedMovieClip
    def ChildrenBlendingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CompressedMovieClip
    def ChildrenBlendingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # CompressedMovieClip
    def Frames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from sc.flash.SC2.MovieClipFrame import MovieClipFrame
            obj = MovieClipFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CompressedMovieClip
    def FramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CompressedMovieClip
    def FramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # CompressedMovieClip
    def FrameElementsOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return None

    # CompressedMovieClip
    def MatrixBankIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CompressedMovieClip
    def ScalingGridIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return None

    # CompressedMovieClip
    def CompressedDataOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def CompressedMovieClipStart(builder):
    builder.StartObject(13)

def Start(builder):
    CompressedMovieClipStart(builder)

def CompressedMovieClipAddId(builder, id):
    builder.PrependUint16Slot(0, id, 0)

def AddId(builder, id):
    CompressedMovieClipAddId(builder, id)

def CompressedMovieClipAddExportNameRefId(builder, exportNameRefId):
    builder.PrependUint32Slot(1, exportNameRefId, None)

def AddExportNameRefId(builder, exportNameRefId):
    CompressedMovieClipAddExportNameRefId(builder, exportNameRefId)

def CompressedMovieClipAddFramerate(builder, framerate):
    builder.PrependUint8Slot(2, framerate, 0)

def AddFramerate(builder, framerate):
    CompressedMovieClipAddFramerate(builder, framerate)

def CompressedMovieClipAddFramesCount(builder, framesCount):
    builder.PrependUint16Slot(3, framesCount, 0)

def AddFramesCount(builder, framesCount):
    CompressedMovieClipAddFramesCount(builder, framesCount)

def CompressedMovieClipAddUnknownBool(builder, unknownBool):
    builder.PrependUint8Slot(4, unknownBool, 0)

def AddUnknownBool(builder, unknownBool):
    CompressedMovieClipAddUnknownBool(builder, unknownBool)

def CompressedMovieClipAddChildrenIds(builder, childrenIds):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(childrenIds), 0)

def AddChildrenIds(builder, childrenIds):
    CompressedMovieClipAddChildrenIds(builder, childrenIds)

def CompressedMovieClipStartChildrenIdsVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartChildrenIdsVector(builder, numElems):
    return CompressedMovieClipStartChildrenIdsVector(builder, numElems)

def CompressedMovieClipCreateChildrenIdsVector(builder, data):
    data = list(data)
    builder.StartVector(2, len(data), 2)
    for item in reversed(data):
        builder.PrependUint16(item)
    return builder.EndVector()

def CreateChildrenIdsVector(builder, data):
    return CompressedMovieClipCreateChildrenIdsVector(builder, data)

def CompressedMovieClipAddChildrenNameRefIds(builder, childrenNameRefIds):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(childrenNameRefIds), 0)

def AddChildrenNameRefIds(builder, childrenNameRefIds):
    CompressedMovieClipAddChildrenNameRefIds(builder, childrenNameRefIds)

def CompressedMovieClipStartChildrenNameRefIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChildrenNameRefIdsVector(builder, numElems):
    return CompressedMovieClipStartChildrenNameRefIdsVector(builder, numElems)

def CompressedMovieClipCreateChildrenNameRefIdsVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateChildrenNameRefIdsVector(builder, data):
    return CompressedMovieClipCreateChildrenNameRefIdsVector(builder, data)

def CompressedMovieClipAddChildrenBlending(builder, childrenBlending):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(childrenBlending), 0)

def AddChildrenBlending(builder, childrenBlending):
    CompressedMovieClipAddChildrenBlending(builder, childrenBlending)

def CompressedMovieClipStartChildrenBlendingVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartChildrenBlendingVector(builder, numElems):
    return CompressedMovieClipStartChildrenBlendingVector(builder, numElems)

def CompressedMovieClipCreateChildrenBlendingVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateChildrenBlendingVector(builder, data):
    return CompressedMovieClipCreateChildrenBlendingVector(builder, data)

def CompressedMovieClipAddFrames(builder, frames):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(frames), 0)

def AddFrames(builder, frames):
    CompressedMovieClipAddFrames(builder, frames)

def CompressedMovieClipStartFramesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartFramesVector(builder, numElems):
    return CompressedMovieClipStartFramesVector(builder, numElems)

def CompressedMovieClipCreateFramesVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateFramesVector(builder, data):
    return CompressedMovieClipCreateFramesVector(builder, data)

def CompressedMovieClipAddFrameElementsOffset(builder, frameElementsOffset):
    builder.PrependUint32Slot(9, frameElementsOffset, None)

def AddFrameElementsOffset(builder, frameElementsOffset):
    CompressedMovieClipAddFrameElementsOffset(builder, frameElementsOffset)

def CompressedMovieClipAddMatrixBankIndex(builder, matrixBankIndex):
    builder.PrependUint32Slot(10, matrixBankIndex, 0)

def AddMatrixBankIndex(builder, matrixBankIndex):
    CompressedMovieClipAddMatrixBankIndex(builder, matrixBankIndex)

def CompressedMovieClipAddScalingGridIndex(builder, scalingGridIndex):
    builder.PrependUint32Slot(11, scalingGridIndex, None)

def AddScalingGridIndex(builder, scalingGridIndex):
    CompressedMovieClipAddScalingGridIndex(builder, scalingGridIndex)

def CompressedMovieClipAddCompressedDataOffset(builder, compressedDataOffset):
    builder.PrependUint32Slot(12, compressedDataOffset, 0)

def AddCompressedDataOffset(builder, compressedDataOffset):
    CompressedMovieClipAddCompressedDataOffset(builder, compressedDataOffset)

def CompressedMovieClipEnd(builder):
    return builder.EndObject()

def End(builder):
    return CompressedMovieClipEnd(builder)
