# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CompressedMovieClips(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CompressedMovieClips()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCompressedMovieClips(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CompressedMovieClips
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CompressedMovieClips
    def Movieclips(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sc.flash.SC2.CompressedMovieClip import CompressedMovieClip
            obj = CompressedMovieClip()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CompressedMovieClips
    def MovieclipsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CompressedMovieClips
    def MovieclipsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def CompressedMovieClipsStart(builder):
    builder.StartObject(1)

def Start(builder):
    CompressedMovieClipsStart(builder)

def CompressedMovieClipsAddMovieclips(builder, movieclips):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(movieclips), 0)

def AddMovieclips(builder, movieclips):
    CompressedMovieClipsAddMovieclips(builder, movieclips)

def CompressedMovieClipsStartMovieclipsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMovieclipsVector(builder, numElems):
    return CompressedMovieClipsStartMovieclipsVector(builder, numElems)

def CompressedMovieClipsCreateMovieclipsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateMovieclipsVector(builder, data):
    return CompressedMovieClipsCreateMovieclipsVector(builder, data)

def CompressedMovieClipsEnd(builder):
    return builder.EndObject()

def End(builder):
    return CompressedMovieClipsEnd(builder)
