# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DataStorage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataStorage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataStorage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DataStorage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # An array of strings that objects from other chunks access by their number 
    # Example: strings[ref_id - 1]
    # DataStorage
    def Strings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # DataStorage
    def StringsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataStorage
    def StringsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # DataStorage
    def Unk2(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # DataStorage
    def Unk2AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # DataStorage
    def Unk2Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataStorage
    def Unk2IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # DataStorage
    def Unk3(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # DataStorage
    def Unk3AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # DataStorage
    def Unk3Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataStorage
    def Unk3IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # DataStorage
    def Rectangles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from sc.flash.SC2.Typing.Rect import Rect
            obj = Rect()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataStorage
    def RectanglesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataStorage
    def RectanglesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # DataStorage
    def MovieclipsFrameElements(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # DataStorage
    def MovieclipsFrameElementsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # DataStorage
    def MovieclipsFrameElementsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataStorage
    def MovieclipsFrameElementsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # DataStorage
    def ShapesBitmapPoins(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # DataStorage
    def ShapesBitmapPoinsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # DataStorage
    def ShapesBitmapPoinsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataStorage
    def ShapesBitmapPoinsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # DataStorage
    def MatrixBanks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sc.flash.SC2.MatrixBank import MatrixBank
            obj = MatrixBank()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataStorage
    def MatrixBanksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataStorage
    def MatrixBanksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def DataStorageStart(builder):
    builder.StartObject(7)

def Start(builder):
    DataStorageStart(builder)

def DataStorageAddStrings(builder, strings):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(strings), 0)

def AddStrings(builder, strings):
    DataStorageAddStrings(builder, strings)

def DataStorageStartStringsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStringsVector(builder, numElems):
    return DataStorageStartStringsVector(builder, numElems)

def DataStorageCreateStringsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateStringsVector(builder, data):
    return DataStorageCreateStringsVector(builder, data)

def DataStorageAddUnk2(builder, unk2):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(unk2), 0)

def AddUnk2(builder, unk2):
    DataStorageAddUnk2(builder, unk2)

def DataStorageStartUnk2Vector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartUnk2Vector(builder, numElems):
    return DataStorageStartUnk2Vector(builder, numElems)

def DataStorageCreateUnk2Vector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateUnk2Vector(builder, data):
    return DataStorageCreateUnk2Vector(builder, data)

def DataStorageAddUnk3(builder, unk3):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(unk3), 0)

def AddUnk3(builder, unk3):
    DataStorageAddUnk3(builder, unk3)

def DataStorageStartUnk3Vector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartUnk3Vector(builder, numElems):
    return DataStorageStartUnk3Vector(builder, numElems)

def DataStorageCreateUnk3Vector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateUnk3Vector(builder, data):
    return DataStorageCreateUnk3Vector(builder, data)

def DataStorageAddRectangles(builder, rectangles):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(rectangles), 0)

def AddRectangles(builder, rectangles):
    DataStorageAddRectangles(builder, rectangles)

def DataStorageStartRectanglesVector(builder, numElems):
    return builder.StartVector(16, numElems, 4)

def StartRectanglesVector(builder, numElems):
    return DataStorageStartRectanglesVector(builder, numElems)

def DataStorageCreateRectanglesVector(builder, data):
    data = list(data)
    builder.StartVector(16, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateRectanglesVector(builder, data):
    return DataStorageCreateRectanglesVector(builder, data)

def DataStorageAddMovieclipsFrameElements(builder, movieclipsFrameElements):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(movieclipsFrameElements), 0)

def AddMovieclipsFrameElements(builder, movieclipsFrameElements):
    DataStorageAddMovieclipsFrameElements(builder, movieclipsFrameElements)

def DataStorageStartMovieclipsFrameElementsVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartMovieclipsFrameElementsVector(builder, numElems):
    return DataStorageStartMovieclipsFrameElementsVector(builder, numElems)

def DataStorageCreateMovieclipsFrameElementsVector(builder, data):
    data = list(data)
    builder.StartVector(2, len(data), 2)
    for item in reversed(data):
        builder.PrependUint16(item)
    return builder.EndVector()

def CreateMovieclipsFrameElementsVector(builder, data):
    return DataStorageCreateMovieclipsFrameElementsVector(builder, data)

def DataStorageAddShapesBitmapPoins(builder, shapesBitmapPoins):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(shapesBitmapPoins), 0)

def AddShapesBitmapPoins(builder, shapesBitmapPoins):
    DataStorageAddShapesBitmapPoins(builder, shapesBitmapPoins)

def DataStorageStartShapesBitmapPoinsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartShapesBitmapPoinsVector(builder, numElems):
    return DataStorageStartShapesBitmapPoinsVector(builder, numElems)

def DataStorageCreateShapesBitmapPoinsVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateShapesBitmapPoinsVector(builder, data):
    return DataStorageCreateShapesBitmapPoinsVector(builder, data)

def DataStorageAddMatrixBanks(builder, matrixBanks):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(matrixBanks), 0)

def AddMatrixBanks(builder, matrixBanks):
    DataStorageAddMatrixBanks(builder, matrixBanks)

def DataStorageStartMatrixBanksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMatrixBanksVector(builder, numElems):
    return DataStorageStartMatrixBanksVector(builder, numElems)

def DataStorageCreateMatrixBanksVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateMatrixBanksVector(builder, data):
    return DataStorageCreateMatrixBanksVector(builder, data)

def DataStorageEnd(builder):
    return builder.EndObject()

def End(builder):
    return DataStorageEnd(builder)
