# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExportNameHash(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExportNameHash()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExportNameHash(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExportNameHash
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExportNameHash
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExportNameHash
    def Hash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ExportNameHash
    def HashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ExportNameHash
    def HashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportNameHash
    def HashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ExportNameHashStart(builder):
    builder.StartObject(2)

def Start(builder):
    ExportNameHashStart(builder)

def ExportNameHashAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ExportNameHashAddName(builder, name)

def ExportNameHashAddHash(builder, hash):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(hash), 0)

def AddHash(builder, hash):
    ExportNameHashAddHash(builder, hash)

def ExportNameHashStartHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartHashVector(builder, numElems):
    return ExportNameHashStartHashVector(builder, numElems)

def ExportNameHashCreateHashVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateHashVector(builder, data):
    return ExportNameHashCreateHashVector(builder, data)

def ExportNameHashEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExportNameHashEnd(builder)
