# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExportNames(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExportNames()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExportNames(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExportNames
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExportNames
    def ObjectIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # ExportNames
    def ObjectIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ExportNames
    def ObjectIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportNames
    def ObjectIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ExportNames
    def NameRefIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ExportNames
    def NameRefIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # ExportNames
    def NameRefIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportNames
    def NameRefIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ExportNamesStart(builder):
    builder.StartObject(2)

def Start(builder):
    ExportNamesStart(builder)

def ExportNamesAddObjectIds(builder, objectIds):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objectIds), 0)

def AddObjectIds(builder, objectIds):
    ExportNamesAddObjectIds(builder, objectIds)

def ExportNamesStartObjectIdsVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartObjectIdsVector(builder, numElems):
    return ExportNamesStartObjectIdsVector(builder, numElems)

def ExportNamesCreateObjectIdsVector(builder, data):
    data = list(data)
    builder.StartVector(2, len(data), 2)
    for item in reversed(data):
        builder.PrependUint16(item)
    return builder.EndVector()

def CreateObjectIdsVector(builder, data):
    return ExportNamesCreateObjectIdsVector(builder, data)

def ExportNamesAddNameRefIds(builder, nameRefIds):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(nameRefIds), 0)

def AddNameRefIds(builder, nameRefIds):
    ExportNamesAddNameRefIds(builder, nameRefIds)

def ExportNamesStartNameRefIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNameRefIdsVector(builder, numElems):
    return ExportNamesStartNameRefIdsVector(builder, numElems)

def ExportNamesCreateNameRefIdsVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateNameRefIdsVector(builder, data):
    return ExportNamesCreateNameRefIdsVector(builder, data)

def ExportNamesEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExportNamesEnd(builder)
