# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExternalMatrixBanks(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExternalMatrixBanks()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExternalMatrixBanks(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExternalMatrixBanks
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExternalMatrixBanks
    def Banks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sc.flash.SC2.ExternalMatrixBank import ExternalMatrixBank
            obj = ExternalMatrixBank()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExternalMatrixBanks
    def BanksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExternalMatrixBanks
    def BanksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ExternalMatrixBanksStart(builder):
    builder.StartObject(1)

def Start(builder):
    ExternalMatrixBanksStart(builder)

def ExternalMatrixBanksAddBanks(builder, banks):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(banks), 0)

def AddBanks(builder, banks):
    ExternalMatrixBanksAddBanks(builder, banks)

def ExternalMatrixBanksStartBanksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBanksVector(builder, numElems):
    return ExternalMatrixBanksStartBanksVector(builder, numElems)

def ExternalMatrixBanksCreateBanksVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateBanksVector(builder, data):
    return ExternalMatrixBanksCreateBanksVector(builder, data)

def ExternalMatrixBanksEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExternalMatrixBanksEnd(builder)
