# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExternalMatrixBank(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExternalMatrixBank()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExternalMatrixBank(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExternalMatrixBank
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExternalMatrixBank
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def CompressedDataOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def CompressedDataSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def DecompressedDataSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def CompressedMatrixDataSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def ShortMatrixDataSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def ShortMatrixCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def FloatMatrixCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def ColorTransformCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def ClipDataOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def ClipDataSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def Unk2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def Unk3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalMatrixBank
    def Unk4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ExternalMatrixBankStart(builder):
    builder.StartObject(14)

def Start(builder):
    ExternalMatrixBankStart(builder)

def ExternalMatrixBankAddIndex(builder, index):
    builder.PrependUint32Slot(0, index, 0)

def AddIndex(builder, index):
    ExternalMatrixBankAddIndex(builder, index)

def ExternalMatrixBankAddCompressedDataOffset(builder, compressedDataOffset):
    builder.PrependUint32Slot(1, compressedDataOffset, 0)

def AddCompressedDataOffset(builder, compressedDataOffset):
    ExternalMatrixBankAddCompressedDataOffset(builder, compressedDataOffset)

def ExternalMatrixBankAddCompressedDataSize(builder, compressedDataSize):
    builder.PrependUint32Slot(2, compressedDataSize, 0)

def AddCompressedDataSize(builder, compressedDataSize):
    ExternalMatrixBankAddCompressedDataSize(builder, compressedDataSize)

def ExternalMatrixBankAddDecompressedDataSize(builder, decompressedDataSize):
    builder.PrependUint32Slot(3, decompressedDataSize, 0)

def AddDecompressedDataSize(builder, decompressedDataSize):
    ExternalMatrixBankAddDecompressedDataSize(builder, decompressedDataSize)

def ExternalMatrixBankAddCompressedMatrixDataSize(builder, compressedMatrixDataSize):
    builder.PrependUint32Slot(4, compressedMatrixDataSize, 0)

def AddCompressedMatrixDataSize(builder, compressedMatrixDataSize):
    ExternalMatrixBankAddCompressedMatrixDataSize(builder, compressedMatrixDataSize)

def ExternalMatrixBankAddShortMatrixDataSize(builder, shortMatrixDataSize):
    builder.PrependUint32Slot(5, shortMatrixDataSize, 0)

def AddShortMatrixDataSize(builder, shortMatrixDataSize):
    ExternalMatrixBankAddShortMatrixDataSize(builder, shortMatrixDataSize)

def ExternalMatrixBankAddShortMatrixCount(builder, shortMatrixCount):
    builder.PrependUint32Slot(6, shortMatrixCount, 0)

def AddShortMatrixCount(builder, shortMatrixCount):
    ExternalMatrixBankAddShortMatrixCount(builder, shortMatrixCount)

def ExternalMatrixBankAddFloatMatrixCount(builder, floatMatrixCount):
    builder.PrependUint32Slot(7, floatMatrixCount, 0)

def AddFloatMatrixCount(builder, floatMatrixCount):
    ExternalMatrixBankAddFloatMatrixCount(builder, floatMatrixCount)

def ExternalMatrixBankAddColorTransformCount(builder, colorTransformCount):
    builder.PrependUint32Slot(8, colorTransformCount, 0)

def AddColorTransformCount(builder, colorTransformCount):
    ExternalMatrixBankAddColorTransformCount(builder, colorTransformCount)

def ExternalMatrixBankAddClipDataOffset(builder, clipDataOffset):
    builder.PrependUint32Slot(9, clipDataOffset, 0)

def AddClipDataOffset(builder, clipDataOffset):
    ExternalMatrixBankAddClipDataOffset(builder, clipDataOffset)

def ExternalMatrixBankAddClipDataSize(builder, clipDataSize):
    builder.PrependUint32Slot(10, clipDataSize, 0)

def AddClipDataSize(builder, clipDataSize):
    ExternalMatrixBankAddClipDataSize(builder, clipDataSize)

def ExternalMatrixBankAddUnk2(builder, unk2):
    builder.PrependUint32Slot(11, unk2, 0)

def AddUnk2(builder, unk2):
    ExternalMatrixBankAddUnk2(builder, unk2)

def ExternalMatrixBankAddUnk3(builder, unk3):
    builder.PrependUint32Slot(12, unk3, 0)

def AddUnk3(builder, unk3):
    ExternalMatrixBankAddUnk3(builder, unk3)

def ExternalMatrixBankAddUnk4(builder, unk4):
    builder.PrependUint32Slot(13, unk4, 0)

def AddUnk4(builder, unk4):
    ExternalMatrixBankAddUnk4(builder, unk4)

def ExternalMatrixBankEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExternalMatrixBankEnd(builder)
