# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FileDescriptor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FileDescriptor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFileDescriptor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FileDescriptor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FileDescriptor
    def TranslationPrecision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def ScalePrecision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def ShapeCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def MovieClipsCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def TextureCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def TextFieldsCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def Unk3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def Unk4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def ResourcesOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def TexturesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def Exports(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sc.flash.SC2.ExportNameHash import ExportNameHash
            obj = ExportNameHash()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FileDescriptor
    def ExportsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FileDescriptor
    def ExportsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # FileDescriptor
    def CompressedSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FileDescriptor
    def ExternalMatrixBankSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def FileDescriptorStart(builder):
    builder.StartObject(13)

def Start(builder):
    FileDescriptorStart(builder)

def FileDescriptorAddTranslationPrecision(builder, translationPrecision):
    builder.PrependUint32Slot(0, translationPrecision, 0)

def AddTranslationPrecision(builder, translationPrecision):
    FileDescriptorAddTranslationPrecision(builder, translationPrecision)

def FileDescriptorAddScalePrecision(builder, scalePrecision):
    builder.PrependUint32Slot(1, scalePrecision, 0)

def AddScalePrecision(builder, scalePrecision):
    FileDescriptorAddScalePrecision(builder, scalePrecision)

def FileDescriptorAddShapeCount(builder, shapeCount):
    builder.PrependUint32Slot(2, shapeCount, 0)

def AddShapeCount(builder, shapeCount):
    FileDescriptorAddShapeCount(builder, shapeCount)

def FileDescriptorAddMovieClipsCount(builder, movieClipsCount):
    builder.PrependUint32Slot(3, movieClipsCount, 0)

def AddMovieClipsCount(builder, movieClipsCount):
    FileDescriptorAddMovieClipsCount(builder, movieClipsCount)

def FileDescriptorAddTextureCount(builder, textureCount):
    builder.PrependUint32Slot(4, textureCount, 0)

def AddTextureCount(builder, textureCount):
    FileDescriptorAddTextureCount(builder, textureCount)

def FileDescriptorAddTextFieldsCount(builder, textFieldsCount):
    builder.PrependUint32Slot(5, textFieldsCount, 0)

def AddTextFieldsCount(builder, textFieldsCount):
    FileDescriptorAddTextFieldsCount(builder, textFieldsCount)

def FileDescriptorAddUnk3(builder, unk3):
    builder.PrependUint32Slot(6, unk3, 0)

def AddUnk3(builder, unk3):
    FileDescriptorAddUnk3(builder, unk3)

def FileDescriptorAddUnk4(builder, unk4):
    builder.PrependUint32Slot(7, unk4, 0)

def AddUnk4(builder, unk4):
    FileDescriptorAddUnk4(builder, unk4)

def FileDescriptorAddResourcesOffset(builder, resourcesOffset):
    builder.PrependUint32Slot(8, resourcesOffset, 0)

def AddResourcesOffset(builder, resourcesOffset):
    FileDescriptorAddResourcesOffset(builder, resourcesOffset)

def FileDescriptorAddTexturesLength(builder, texturesLength):
    builder.PrependUint32Slot(9, texturesLength, 0)

def AddTexturesLength(builder, texturesLength):
    FileDescriptorAddTexturesLength(builder, texturesLength)

def FileDescriptorAddExports(builder, exports):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(exports), 0)

def AddExports(builder, exports):
    FileDescriptorAddExports(builder, exports)

def FileDescriptorStartExportsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExportsVector(builder, numElems):
    return FileDescriptorStartExportsVector(builder, numElems)

def FileDescriptorCreateExportsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateExportsVector(builder, data):
    return FileDescriptorCreateExportsVector(builder, data)

def FileDescriptorAddCompressedSize(builder, compressedSize):
    builder.PrependUint32Slot(11, compressedSize, 0)

def AddCompressedSize(builder, compressedSize):
    FileDescriptorAddCompressedSize(builder, compressedSize)

def FileDescriptorAddExternalMatrixBankSize(builder, externalMatrixBankSize):
    builder.PrependUint32Slot(12, externalMatrixBankSize, 0)

def AddExternalMatrixBankSize(builder, externalMatrixBankSize):
    FileDescriptorAddExternalMatrixBankSize(builder, externalMatrixBankSize)

def FileDescriptorEnd(builder):
    return builder.EndObject()

def End(builder):
    return FileDescriptorEnd(builder)
