# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MovieClipModifiers(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MovieClipModifiers()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMovieClipModifiers(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MovieClipModifiers
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MovieClipModifiers
    def Modifiers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from sc.flash.SC2.MovieClipModifier import MovieClipModifier
            obj = MovieClipModifier()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MovieClipModifiers
    def ModifiersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MovieClipModifiers
    def ModifiersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def MovieClipModifiersStart(builder):
    builder.StartObject(1)

def Start(builder):
    MovieClipModifiersStart(builder)

def MovieClipModifiersAddModifiers(builder, modifiers):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(modifiers), 0)

def AddModifiers(builder, modifiers):
    MovieClipModifiersAddModifiers(builder, modifiers)

def MovieClipModifiersStartModifiersVector(builder, numElems):
    return builder.StartVector(4, numElems, 2)

def StartModifiersVector(builder, numElems):
    return MovieClipModifiersStartModifiersVector(builder, numElems)

def MovieClipModifiersCreateModifiersVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateModifiersVector(builder, data):
    return MovieClipModifiersCreateModifiersVector(builder, data)

def MovieClipModifiersEnd(builder):
    return builder.EndObject()

def End(builder):
    return MovieClipModifiersEnd(builder)
