# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MovieClipModifier(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # MovieClipModifier
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MovieClipModifier
    def Id(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MovieClipModifier
    def Type(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateMovieClipModifier(builder, id, type):
    builder.Prep(2, 4)
    builder.Pad(1)
    builder.PrependUint8(type)
    builder.PrependUint16(id)
    return builder.Offset()
