# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MovieClip(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MovieClip()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMovieClip(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MovieClip
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MovieClip
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # MovieClip
    def ExportNameRefId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return None

    # MovieClip
    def Framerate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MovieClip
    def FramesCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # MovieClip
    def UnknownBool(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MovieClip
    def ChildrenIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # MovieClip
    def ChildrenIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # MovieClip
    def ChildrenIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MovieClip
    def ChildrenIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # MovieClip
    def ChildrenNameRefIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MovieClip
    def ChildrenNameRefIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # MovieClip
    def ChildrenNameRefIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MovieClip
    def ChildrenNameRefIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # MovieClip
    def ChildrenBlending(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # MovieClip
    def ChildrenBlendingAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # MovieClip
    def ChildrenBlendingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MovieClip
    def ChildrenBlendingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # MovieClip
    def Frames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from sc.flash.SC2.MovieClipFrame import MovieClipFrame
            obj = MovieClipFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MovieClip
    def FramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MovieClip
    def FramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # MovieClip
    def FrameElementsOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 4294967295

    # MovieClip
    def MatrixBankIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MovieClip
    def ScalingGridIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return None

    # MovieClip
    def ShortFrames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 2
            from sc.flash.SC2.MovieClipShortFrame import MovieClipShortFrame
            obj = MovieClipShortFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MovieClip
    def ShortFramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MovieClip
    def ShortFramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

def MovieClipStart(builder):
    builder.StartObject(13)

def Start(builder):
    MovieClipStart(builder)

def MovieClipAddId(builder, id):
    builder.PrependUint16Slot(0, id, 0)

def AddId(builder, id):
    MovieClipAddId(builder, id)

def MovieClipAddExportNameRefId(builder, exportNameRefId):
    builder.PrependUint32Slot(1, exportNameRefId, None)

def AddExportNameRefId(builder, exportNameRefId):
    MovieClipAddExportNameRefId(builder, exportNameRefId)

def MovieClipAddFramerate(builder, framerate):
    builder.PrependUint8Slot(2, framerate, 0)

def AddFramerate(builder, framerate):
    MovieClipAddFramerate(builder, framerate)

def MovieClipAddFramesCount(builder, framesCount):
    builder.PrependUint16Slot(3, framesCount, 0)

def AddFramesCount(builder, framesCount):
    MovieClipAddFramesCount(builder, framesCount)

def MovieClipAddUnknownBool(builder, unknownBool):
    builder.PrependUint8Slot(4, unknownBool, 0)

def AddUnknownBool(builder, unknownBool):
    MovieClipAddUnknownBool(builder, unknownBool)

def MovieClipAddChildrenIds(builder, childrenIds):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(childrenIds), 0)

def AddChildrenIds(builder, childrenIds):
    MovieClipAddChildrenIds(builder, childrenIds)

def MovieClipStartChildrenIdsVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartChildrenIdsVector(builder, numElems):
    return MovieClipStartChildrenIdsVector(builder, numElems)

def MovieClipCreateChildrenIdsVector(builder, data):
    data = list(data)
    builder.StartVector(2, len(data), 2)
    for item in reversed(data):
        builder.PrependUint16(item)
    return builder.EndVector()

def CreateChildrenIdsVector(builder, data):
    return MovieClipCreateChildrenIdsVector(builder, data)

def MovieClipAddChildrenNameRefIds(builder, childrenNameRefIds):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(childrenNameRefIds), 0)

def AddChildrenNameRefIds(builder, childrenNameRefIds):
    MovieClipAddChildrenNameRefIds(builder, childrenNameRefIds)

def MovieClipStartChildrenNameRefIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChildrenNameRefIdsVector(builder, numElems):
    return MovieClipStartChildrenNameRefIdsVector(builder, numElems)

def MovieClipCreateChildrenNameRefIdsVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateChildrenNameRefIdsVector(builder, data):
    return MovieClipCreateChildrenNameRefIdsVector(builder, data)

def MovieClipAddChildrenBlending(builder, childrenBlending):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(childrenBlending), 0)

def AddChildrenBlending(builder, childrenBlending):
    MovieClipAddChildrenBlending(builder, childrenBlending)

def MovieClipStartChildrenBlendingVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartChildrenBlendingVector(builder, numElems):
    return MovieClipStartChildrenBlendingVector(builder, numElems)

def MovieClipCreateChildrenBlendingVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateChildrenBlendingVector(builder, data):
    return MovieClipCreateChildrenBlendingVector(builder, data)

def MovieClipAddFrames(builder, frames):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(frames), 0)

def AddFrames(builder, frames):
    MovieClipAddFrames(builder, frames)

def MovieClipStartFramesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartFramesVector(builder, numElems):
    return MovieClipStartFramesVector(builder, numElems)

def MovieClipCreateFramesVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateFramesVector(builder, data):
    return MovieClipCreateFramesVector(builder, data)

def MovieClipAddFrameElementsOffset(builder, frameElementsOffset):
    builder.PrependUint32Slot(9, frameElementsOffset, 4294967295)

def AddFrameElementsOffset(builder, frameElementsOffset):
    MovieClipAddFrameElementsOffset(builder, frameElementsOffset)

def MovieClipAddMatrixBankIndex(builder, matrixBankIndex):
    builder.PrependUint32Slot(10, matrixBankIndex, 0)

def AddMatrixBankIndex(builder, matrixBankIndex):
    MovieClipAddMatrixBankIndex(builder, matrixBankIndex)

def MovieClipAddScalingGridIndex(builder, scalingGridIndex):
    builder.PrependUint32Slot(11, scalingGridIndex, None)

def AddScalingGridIndex(builder, scalingGridIndex):
    MovieClipAddScalingGridIndex(builder, scalingGridIndex)

def MovieClipAddShortFrames(builder, shortFrames):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(shortFrames), 0)

def AddShortFrames(builder, shortFrames):
    MovieClipAddShortFrames(builder, shortFrames)

def MovieClipStartShortFramesVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartShortFramesVector(builder, numElems):
    return MovieClipStartShortFramesVector(builder, numElems)

def MovieClipCreateShortFramesVector(builder, data):
    data = list(data)
    builder.StartVector(2, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateShortFramesVector(builder, data):
    return MovieClipCreateShortFramesVector(builder, data)

def MovieClipEnd(builder):
    return builder.EndObject()

def End(builder):
    return MovieClipEnd(builder)
