# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MovieClips(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MovieClips()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMovieClips(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MovieClips
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MovieClips
    def Movieclips(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sc.flash.SC2.MovieClip import MovieClip
            obj = MovieClip()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MovieClips
    def MovieclipsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MovieClips
    def MovieclipsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def MovieClipsStart(builder):
    builder.StartObject(1)

def Start(builder):
    MovieClipsStart(builder)

def MovieClipsAddMovieclips(builder, movieclips):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(movieclips), 0)

def AddMovieclips(builder, movieclips):
    MovieClipsAddMovieclips(builder, movieclips)

def MovieClipsStartMovieclipsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMovieclipsVector(builder, numElems):
    return MovieClipsStartMovieclipsVector(builder, numElems)

def MovieClipsCreateMovieclipsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateMovieclipsVector(builder, data):
    return MovieClipsCreateMovieclipsVector(builder, data)

def MovieClipsEnd(builder):
    return builder.EndObject()

def End(builder):
    return MovieClipsEnd(builder)
