# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MovieClipShortFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 2

    # MovieClipShortFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MovieClipShortFrame
    def UsedTransform(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateMovieClipShortFrame(builder, usedTransform):
    builder.Prep(2, 2)
    builder.PrependUint16(usedTransform)
    return builder.Offset()
