# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MovieClipFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # MovieClipFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MovieClipFrame
    def UsedTransform(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MovieClipFrame
    def LabelRefId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateMovieClipFrame(builder, usedTransform, labelRefId):
    builder.Prep(4, 8)
    builder.PrependUint32(labelRefId)
    builder.PrependUint32(usedTransform)
    return builder.Offset()
