# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShapeDrawBitmapCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # ShapeDrawBitmapCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShapeDrawBitmapCommand
    def Unk1(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ShapeDrawBitmapCommand
    def TextureIndex(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # ShapeDrawBitmapCommand
    def PointsCount(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ShapeDrawBitmapCommand
    def PointsOffset(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateShapeDrawBitmapCommand(builder, unk1, textureIndex, pointsCount, pointsOffset):
    builder.Prep(4, 16)
    builder.PrependUint32(pointsOffset)
    builder.PrependUint32(pointsCount)
    builder.PrependUint32(textureIndex)
    builder.PrependUint32(unk1)
    return builder.Offset()
