# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Shape(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Shape()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShape(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Shape
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Shape
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Shape
    def Commands(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from sc.flash.SC2.ShapeDrawBitmapCommand import ShapeDrawBitmapCommand
            obj = ShapeDrawBitmapCommand()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shape
    def CommandsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shape
    def CommandsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ShapeStart(builder):
    builder.StartObject(2)

def Start(builder):
    ShapeStart(builder)

def ShapeAddId(builder, id):
    builder.PrependUint16Slot(0, id, 0)

def AddId(builder, id):
    ShapeAddId(builder, id)

def ShapeAddCommands(builder, commands):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(commands), 0)

def AddCommands(builder, commands):
    ShapeAddCommands(builder, commands)

def ShapeStartCommandsVector(builder, numElems):
    return builder.StartVector(16, numElems, 4)

def StartCommandsVector(builder, numElems):
    return ShapeStartCommandsVector(builder, numElems)

def ShapeCreateCommandsVector(builder, data):
    data = list(data)
    builder.StartVector(16, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateCommandsVector(builder, data):
    return ShapeCreateCommandsVector(builder, data)

def ShapeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShapeEnd(builder)
