# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Shapes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Shapes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShapes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Shapes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Shapes
    def Shapes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sc.flash.SC2.Shape import Shape
            obj = Shape()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shapes
    def ShapesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shapes
    def ShapesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ShapesStart(builder):
    builder.StartObject(1)

def Start(builder):
    ShapesStart(builder)

def ShapesAddShapes(builder, shapes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shapes), 0)

def AddShapes(builder, shapes):
    ShapesAddShapes(builder, shapes)

def ShapesStartShapesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShapesVector(builder, numElems):
    return ShapesStartShapesVector(builder, numElems)

def ShapesCreateShapesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateShapesVector(builder, data):
    return ShapesCreateShapesVector(builder, data)

def ShapesEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShapesEnd(builder)
