# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TextField(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 40

    # TextField
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TextField
    def Id(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TextField
    def Unused1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # TextField
    def FontNameRefId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # TextField
    def Left(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # TextField
    def Top(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # TextField
    def Right(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # TextField
    def Bottom(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))
    # TextField
    def FontColor(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # TextField
    def OutlineColor(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # TextField
    def TextRefId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))
    # TextField
    def TypographyRefId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(28))
    # TextField
    def Styles(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # TextField
    def Align(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(33))
    # TextField
    def FontSize(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(34))
    # TextField
    def Unused2(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(35))
    # TextField
    def OutlineStrength(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36))

def CreateTextField(builder, id, unused1, fontNameRefId, left, top, right, bottom, fontColor, outlineColor, textRefId, typographyRefId, styles, align, fontSize, unused2, outlineStrength):
    builder.Prep(4, 40)
    builder.Pad(2)
    builder.PrependUint16(outlineStrength)
    builder.PrependUint8(unused2)
    builder.PrependUint8(fontSize)
    builder.PrependUint8(align)
    builder.PrependUint8(styles)
    builder.PrependUint32(typographyRefId)
    builder.PrependUint32(textRefId)
    builder.PrependUint32(outlineColor)
    builder.PrependUint32(fontColor)
    builder.PrependInt16(bottom)
    builder.PrependInt16(right)
    builder.PrependInt16(top)
    builder.PrependInt16(left)
    builder.PrependUint32(fontNameRefId)
    builder.PrependUint16(unused1)
    builder.PrependUint16(id)
    return builder.Offset()
