# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Textures(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Textures()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTextures(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Textures
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Textures
    def Textures(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sc.flash.SC2.TextureSet import TextureSet
            obj = TextureSet()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Textures
    def TexturesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Textures
    def TexturesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TexturesStart(builder):
    builder.StartObject(1)

def Start(builder):
    TexturesStart(builder)

def TexturesAddTextures(builder, textures):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(textures), 0)

def AddTextures(builder, textures):
    TexturesAddTextures(builder, textures)

def TexturesStartTexturesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTexturesVector(builder, numElems):
    return TexturesStartTexturesVector(builder, numElems)

def TexturesCreateTexturesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateTexturesVector(builder, data):
    return TexturesCreateTexturesVector(builder, data)

def TexturesEnd(builder):
    return builder.EndObject()

def End(builder):
    return TexturesEnd(builder)
