# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TextureData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TextureData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTextureData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TextureData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TextureData
    def TextureFormat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TextureData
    def PixelType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TextureData
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TextureData
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TextureData
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # TextureData
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # TextureData
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TextureData
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # TextureData
    def ExternalTexture(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def TextureDataStart(builder):
    builder.StartObject(6)

def Start(builder):
    TextureDataStart(builder)

def TextureDataAddTextureFormat(builder, textureFormat):
    builder.PrependUint8Slot(0, textureFormat, 0)

def AddTextureFormat(builder, textureFormat):
    TextureDataAddTextureFormat(builder, textureFormat)

def TextureDataAddPixelType(builder, pixelType):
    builder.PrependUint8Slot(1, pixelType, 0)

def AddPixelType(builder, pixelType):
    TextureDataAddPixelType(builder, pixelType)

def TextureDataAddWidth(builder, width):
    builder.PrependUint16Slot(2, width, 0)

def AddWidth(builder, width):
    TextureDataAddWidth(builder, width)

def TextureDataAddHeight(builder, height):
    builder.PrependUint16Slot(3, height, 0)

def AddHeight(builder, height):
    TextureDataAddHeight(builder, height)

def TextureDataAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    TextureDataAddData(builder, data)

def TextureDataStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return TextureDataStartDataVector(builder, numElems)

def TextureDataCreateDataVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateDataVector(builder, data):
    return TextureDataCreateDataVector(builder, data)

def TextureDataAddExternalTexture(builder, externalTexture):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(externalTexture), 0)

def AddExternalTexture(builder, externalTexture):
    TextureDataAddExternalTexture(builder, externalTexture)

def TextureDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return TextureDataEnd(builder)
