# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TextureSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TextureSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTextureSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TextureSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TextureSet
    def Lowres(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sc.flash.SC2.TextureData import TextureData
            obj = TextureData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TextureSet
    def Highres(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sc.flash.SC2.TextureData import TextureData
            obj = TextureData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TextureSetStart(builder):
    builder.StartObject(2)

def Start(builder):
    TextureSetStart(builder)

def TextureSetAddLowres(builder, lowres):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(lowres), 0)

def AddLowres(builder, lowres):
    TextureSetAddLowres(builder, lowres)

def TextureSetAddHighres(builder, highres):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(highres), 0)

def AddHighres(builder, highres):
    TextureSetAddHighres(builder, highres)

def TextureSetEnd(builder):
    return builder.EndObject()

def End(builder):
    return TextureSetEnd(builder)
