# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SC2

class TextFieldStyle(object):
    unknown_flag3 = 1
    has_outline = 2
    bold = 4
    italic = 8
    is_multiline = 16
    unknown_flag = 32
    auto_kern = 64
